name: CI
on:
  push:
    branches: [ main ]
jobs:
  main_jbb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: quarto-dev/quarto-actions/render@v2
        with:
          path: dashboard.qmd
#      - name: Do shit
#        run: mkdir output; quarto render dashboard.qmd --output-dir output
#      - uses: actions/upload-artifact@v4
#        with:
#          name: dashboard
#          path: output/dashboard.html
